---
title: "HintzmanReplication"
author: "Mark Rayev"
date: "October 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Storing data structure in one list (list of vectors, lists, matrices)

library (lsa)

list_append <- function (input, ...){
input <- c(input, list(...))
  return(input)
}

#Distort prototype
#Input - Distorted matrix
#Source - A, B, or C
#Times - Low-level or High-level distortions

distortion_function <- function (input, source, times) {

  for(i in 1:times) {
    #Choose where to change starting from 11 to 23
      element <-sample(11:length(source),1)
    #Distort  
      input[element] <- source [element] * -1
  }
  #returning distort
  return(input)
}


#Size of memory: 3, 6, or 9 AND number of distortions
#source - A, B, or C
#dest - list to store data for matrix
#Iter - 3, 6, or 9 memory size
#dist_num - low level (2) or high level (4)


memorySize_function <- function (source, iter, dist_num) {

  temp<-source
  dest <- list()
  
  #Temp - distortation array
  
  for(i in 1:iter) { 
        temp <-distortion_function(temp, source, dist_num)
  #Temporary storage
        dest <- list_append(dest,temp)
  }
  #List of distorted vectors
  num_distortion_matrix <- matrix(unlist(dest), byrow=TRUE, nrow=length(dest) )

}

#Function to run A, B, or C
#Source- A, B, or C
#Dest_list - storage
numDistortion_function <- function (source, dest_list) {
  #CLEAN LIST after each distortion
  
  
  #Creating matrix of lists of distorted vectors
  #source - A, B, or C
  
  distortion_matrix <- memorySize_function (source, 3, 2)
  
  dest_list <- list_append(dest_list, distortion_matrix)
  
  
  distortion_matrix <- memorySize_function (source, 6, 2)
  
  dest_list <- list_append(dest_list, distortion_matrix)
  
  
  distortion_matrix <- memorySize_function (source, 9, 2)
  
  dest_list <- list_append(dest_list, distortion_matrix)
  
  
  
  distortion_matrix <- memorySize_function (source,  3, 4)
  
  dest_list <- list_append(dest_list, distortion_matrix)
  
  
  distortion_matrix <- memorySize_function (source,  6, 4)
  
  dest_list <- list_append(dest_list, distortion_matrix)
  
  
  distortion_matrix <- memorySize_function (source,  9, 4)
  
  dest_list <- list_append(dest_list, distortion_matrix)

}

get_echo <- function(probe, mem) {
    # compute similarities between probe and memories
    sim_vals <- c()
    for (m in 1:dim(mem)[1]) {
        sim_vals[m] <- cosine(probe, mem[m, ])  
    }
    # Weight memories by similarity
    weighted_memory <- mem * (sim_vals^3)  

    summed_echo <- colSums(weighted_memory)
    return(summed_echo)
}

mat_list <- list()

mat_list_B <- list()

mat_list_C <- list()

A <- sample( c(1,-1), 23, replace=TRUE)

mat_list <- numDistortion_function(A, mat_list)

mat_list_A <- list()
mat_list_A <- numDistortion_function(A, mat_list_A)

B <- sample( c(1,-1), 23, replace=TRUE)

mat_list <- numDistortion_function(B, mat_list)


mat_list_B <- list()
mat_list_B <- numDistortion_function(B, mat_list_B)

C <- sample( c(1,-1), 23, replace=TRUE)

mat_list <- numDistortion_function(C, mat_list)

 
mat_list_C <- list()
mat_list_C <- numDistortion_function(C, mat_list_C)

#Send category name with empty features 11-23
desired_prob_A <-  c(A[1:10], rep(0,13))

desired_echo_A <- get_echo(desired_prob_A, mat_list_A[[1]]) 

#How similar is echo to prototype?
pearson_cor <- cor(desired_echo_A[11:23], A[11:23])

cos_cor <- cosine(desired_echo_A[11:23], A[11:23])


library(ggplot2)

#echo and probe representation
activations <- c(A[11:23], desired_echo[11:23])
cue <- rep(c("Original", "Echo"), each=13)
neuron_unit <- rep(seq(1:13) ,2)
dframe <- data.frame(cue, neuron_unit, activations)

ggplot(data=dframe, aes(y=activations, x=neuron_unit))+
  geom_bar(stat="identity", position = position_dodge(), fill = "gray") +
  theme_classic(base_size = 12) +
  ylab("Activation") +
  xlab("Position") + 
  facet_wrap(~cue)


comb_list <- c(A,B,C)

countA = 1
countB = 1

#Ambiguous Recall Problem (Empty Category)

cat_probe_A <- c(rep(0, 10), A[11:23])
cat_echo_A <- get_echo(cat_probe_A, mat_list_A[[3]])

cat_pearson_cor <- cor(cat_echo_A[1:10], A[1:10])

cat_cos_cor <- cosine(cat_echo_A[1:10], A[1:10])



```


